// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuL1yxsr-fQNdy9kFhGM7F3400Yv-NBUQ',
    appId: '1:468745474276:web:1c4885ee9021a47f589cf1',
    messagingSenderId: '468745474276',
    projectId: 'concertapp-adb78',
    authDomain: 'concertapp-adb78.firebaseapp.com',
    storageBucket: 'concertapp-adb78.firebasestorage.app',
    measurementId: 'G-MK3FC7XV65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPjQnPSSDab0pHecrSQZVeMMT3kkOdZMw',
    appId: '1:468745474276:android:6dfa1352f84fa397589cf1',
    messagingSenderId: '468745474276',
    projectId: 'concertapp-adb78',
    storageBucket: 'concertapp-adb78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSUuQQA18467mfJx2XzodhD0OdNAEOilA',
    appId: '1:468745474276:ios:5d768d4fa627ea1d589cf1',
    messagingSenderId: '468745474276',
    projectId: 'concertapp-adb78',
    storageBucket: 'concertapp-adb78.firebasestorage.app',
    iosBundleId: 'com.example.concert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSUuQQA18467mfJx2XzodhD0OdNAEOilA',
    appId: '1:468745474276:ios:5d768d4fa627ea1d589cf1',
    messagingSenderId: '468745474276',
    projectId: 'concertapp-adb78',
    storageBucket: 'concertapp-adb78.firebasestorage.app',
    iosBundleId: 'com.example.concert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuL1yxsr-fQNdy9kFhGM7F3400Yv-NBUQ',
    appId: '1:468745474276:web:502f643ee3a4b3b0589cf1',
    messagingSenderId: '468745474276',
    projectId: 'concertapp-adb78',
    authDomain: 'concertapp-adb78.firebaseapp.com',
    storageBucket: 'concertapp-adb78.firebasestorage.app',
    measurementId: 'G-2VBW5DPC8P',
  );
}
